name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.35f1

      - name: Build Spoons
        id: build
        run: |
          /opt/unity/Editor/Unity -batchmode -projectPath . -buildTarget StandaloneWindows64 -quit -nographice -logFile -buildOutput ./Build/Windows/Spoons.exe
          zip -r Build/Spoons.zip Build/Windows

      - name: Upload build as release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Build/Spoons.zip
          asset_name: Spoons.zip
          asset_content_type: application/zip